version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: houses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: house_price_predictor
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db 
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_PORT: 5432
      DB_DATABASE: houses

volumes:
  postgres_data:
